[package]
name = "roguelike"
version = "0.1.0"
edition = "2021"


[dependencies]
# version = "0.15"
tcod = { git = "https://github.com/tomassedovic/tcod-rs.git", features = ["serialization"] }
rand = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
